### PR TITLE
Grammar correction in the README.md file

### PR DESCRIPTION
**Pull request by scarecrow21**
I've corrected the grammar in the readme.md file.

### CODE REVIEW

**Comment by romandev** [comment]
@scarecrow21 
Thank you for this change.
Could you update your name and email in AUTHORS file? (The name should keep in alphabetical order)

**Comment by scarecrow21** [comment]
Sure. Done.

**Comment by yjaeseok** [comment]
Could you add author file update at this patch?
It is a this project's contribution rule.

:)

**Comment by scarecrow21** [comment]
I'm sorry. I'm a new to open source. Could you please elaborate what i have to do?

**Comment by yjaeseok** [comment]
Do you use git command line tools? 
or.. how do you do Pull Request on this project?

**Comment by scarecrow21** [comment]
I use command line. But for this PR, I did it using Github itself.

**Comment by scarecrow21** [comment]
You want me to create a separate branch and push it instead of using the master?

**Comment by yjaeseok** [comment]
Okay, first clone your absolute project in a local storage

```shell
$ git clone https://github.com/scarecrow21/absolute.git
```

and then add upstream repository

```shell
$ cd absolute
$ git remote add upstream https://github.com/lunchclass/absolute.git
```

next switch your patch branch
```shell
$ git checkout patch-1
```

and then, add your name and email to AUTHORS.md file. with alphabet ordering.

last push your change in upstream
```shell
$ git add .
$ git commit -m "Add author scarescrow21"
$ git push origin patch-1
```

finish ! please try it. :)

**Comment by scarecrow21** [comment]
Done. Please tell me if anything else is required.

**Comment by yjaeseok** [comment]
Great !! wait for @romandev approve. !

Thank you for your contribution. @scarecrow21

**Comment by yjaeseok** [comment]
lgtm

**Pull request merged**
