### PR TITLE
 Fix wrong example in contributing.md

### PR DESCRIPTION
**Pull request by hyungheo**
Change one of duplicated function to bar() from foo() in example.

ISSUE=none

### CODE REVIEW

**Comment by romandev** [comment]
@hyungheo any update? If you don't want to continue this work, I'll close this.

**Comment by hyungheo** [comment]
DONE

It has been updated

**Comment by romandev** [comment]
@hyungheo You have to update PR commit description as well?

**Comment by hyungheo** [comment]
DONE

Comment of PR has been  also updated

**Pull request merged**
